README.md

#
Just updating the readme to the right order
https://littleeinsteinchildcare.atlassian.net/browse/LEC-26
1. Updated readme file
N/A

Updated read me for front end

---

src/components/introduction/SaveName.tsx

#
Changed SaveName.tsx to demonstrate succesful push and Jira
https://littleeinsteinchildcare.atlassian.net/browse/LEC-34?atlOrigin=eyJpIjoiNTIzNTI3M2E2ZGZmNGI3Mzk1YTEzNGZhNjYwYzYzNjgiLCJwIjoiaiJ9
1. SaveName.tsx -- Name changed to "Matt Lafferty"
1. run npm run dev
2. Go to localhost URL to see name change

LEC-34 Frontend push demo

---

src/components/introduction/SaveName.tsx

#
Added my name
https://littleeinsteinchildcare.atlassian.net/browse/LEC-32
1. added my name
2. added my name
3. added my name
1. Do "npm run dev"
2. Go to localhost
3. Check name change
During set-up, this line "pre-commit install --hook-type" didn't work for me, but I kinda proceeded and passed "pre-commit run --all-files" so just proceeded.

LEC-32 did set up and added name

---

src/components/introduction/SaveName.tsx

#
https://littleeinsteinchildcare.atlassian.net/browse/LEC-31
1. Added my name to the SaveName component
1. run 'npm run dev'
2. See my name displayed on screen

LEC-31 make a push

---

src/components/introduction/SaveName.tsx

#
I included my name 
https://littleeinsteinchildcare.atlassian.net/browse/LEC-28
1. my name 
2. added my name 
3. my name was added lol 
1. check your localhost 
2. is my name there ? 
3. if my name appears then golden 
- [x ] My code follows the style guidelines of this project.

LEC-28 WTF

---

.github/CODEOWNERS
src/assets/test.tsx
src/components/introduction/SaveName.tsx
src/patterns/test.tsx
src/styles/test.tsx

#
Just adding my name  and some files so the dir would get pushed
https://littleeinsteinchildcare.atlassian.net/browse/LEC-27
1. Added name
2. Added placeholder files
3. Added code owner file
1. Pull and run

Wrote my name and added placeholder files to hold structure

---

src/components/introduction/SaveName.tsx

#
I added my name to SaveName.tsx so that it can be displayed on the locally hosted web page.
[Link the the ticket.](https://littleeinsteinchildcare.atlassian.net/jira/software/projects/LEC/boards/1?selectedIssue=LEC-35)
1. Added my name to SaveName.tsx
1. git fetch origin
2. git checkout -b LEC-35-make-a-push-eddie
3. npm install
4. npm run dev

LEC-35 Added my name to SaveName.tsx

---

.github/PULL_REQUEST_TEMPLATE.md

#
Tired of copying and pasting the ticket. So now we should just be able to replace the ## with our ticket number
1. Just added majority of the link
N/A

Want to make some adjustment to pull template

---

.github/workflows/ci.yml
tsconfig.node.json
vite.config.js

#
Experimenting with workflow that will run our site and make sure it builds and starts. Saving us time from having to pull and check. In the future We can build up this workflow to run the tests as well. 
For now  I will be testing it by pushing to our workflow-research branch. 
<https://littleeinsteinchildcare.atlassian.net/browse/LEC-59>
1. added a workflow
N/A
This is just for reasearch purposes at this moment. Just wanting to check something out.

[LEC-59] experminting with workflow

---

package-lock.json
package.json
src/auth/authConfig.ts
src/auth/hooks/authProvider.tsx
src/main.tsx
src/pages/home/Home.tsx
src/pages/signIn/SignIn.tsx

#
Linking front to back in auth
<https://littleeinsteinchildcare.atlassian.net/browse/LEC-69>
1. Have to use react 18 to use stable msal
2. Signin with azure
1. Pull
2. Run and sign in

[LEC-69] linking front to back auth

---

src/auth/authConfig.ts
src/components/navbar/Navbar.tsx
src/pages/signIn/SignIn.tsx

This PR resolves bug in the authentication UI state by properly syncing the navbar and sign-in flow with MSAL authentication status. It ensures that the authenticated user's info is displayed correctly and removes problematic logic that caused redundant logout/login behavior.
https://littleeinsteinchildcare.atlassian.net/jira/software/projects/LEC/boards/1?selectedIssue=LEC-92
1. **Updated Navbar Component (`src/components/navbar/Navbar.tsx`)**
- Integrated MSAL hooks to track authentication state.
- Conditionally rendered authenticated user info or sign-in button.
- Added `Sign Out` button with `logoutPopup` functionality.
2. **Updated SignIn Page (`src/pages/signIn/SignIn.tsx`)**
- Added automatic redirect to homepage when user is already authenticated.
- Removed unnecessary logout …

Lec 92 Fix authentication UI and login flow inconsistencies

---

src/auth/authConfig.ts
src/components/navbar/Navbar.tsx
src/pages/signIn/SignIn.tsx

* Resolve issues in the authentication-related UI state
* Update scopes & prompts for MSAL
#
<https://littleeinsteinchildcare.atlassian.net/browse/LEC-##>
1. Change 1
2. Change 2
1. Step 1
2. Step 2

Lec 92 Fix authentication UI and login flow inconsistencies (#22)

---

src/App.tsx
src/pages/docs/Docs.tsx

#
Docs Page to Test API Routes
https://littleeinsteinchildcare.atlassian.net/browse/LEC-93
- Docs page and route

Docs API Test Page

---

src/App.tsx
src/components/calendar/Calendar.tsx
src/components/calendar/EventForm.tsx
src/i18n/en.ts
src/i18n/es.ts
src/pages/calendar/Events.tsx

#
<https://littleeinsteinchildcare.atlassian.net/browse/LEC-67>
1. A new EventForm component in `src/components/calendar/EventForm.tsx` with:
- Fields for title, date, start time, end time, location, and description.
- Form validation.
- Submit and cancel buttons.
2. A new Events page in `src/pages/calendar/Events.tsx` that:
- Hosts the EventForm component
- Shows a success message after event creation.
- Redirects back to the calendar page after successful submission.
3. Updates to the Calendar component with:
- A "Create Event" button that navigates to the Events page.
4. Translations for both English and Spanish.
5. Routes configured in App.tsx.
1. npm install
2. npm run dev
3. Visit `http://localhost:5173/calendar`
4. Click on "Create Event".
Things to note:
1. Currently, the events …

LEC-67 Create events page with form component for calendar module

---

src/App.tsx
src/components/admin/Banner.tsx
src/components/navbar/Navbar.tsx
src/context/BannerContext.tsx
src/hooks/useAdminCheck.ts
src/i18n/en.ts
src/i18n/es.ts
src/main.tsx
src/pages/admin/Admin.tsx

#
- admin page
-admin can set weather, close, or custom in /admin
-/admin only requires sign in right now, no role-based RBAC or admin only permissions yet
-drop down menu to select banner type, and if custom message needed
-duration defaults to 24hrs, also has clear banner to remove it early 
- banner
-has global context in BannerContext to manage banner state (type, message, expires)
-when app loads, BannerProvider checks local storage for now to either display banner or remove if expired
-set/clearBanner change the state 
-banner can be dismissed temporarily by users (state is still there tho, just visual)
*note on third commit after PR
-just added a hook folder and a hook file (no implementation yet) to prepare for backend when the site-admin group is added and when the /api/admin …

LEC-98 notification banner

---

src/components/footer/footerConnectLinks.tsx
src/components/footer/footerContactLinks.tsx
src/components/home/location.tsx
src/pages/contactUs/ContactUs.tsx

#
Email and phone number updated to show sponsor actual email and number 
<https://littleeinsteinchildcare.atlassian.net/browse/LEC-115>
1. Change 1 : Email went from stand in email to littleeinstein77@yahoo.com
3. Change 2: Phone number changed from stand in to (971)275-2815 
Not applicable, No real code was changed. 
1. Step 1 
2. Step 2
- [x ] My code follows the style guidelines of this project.
- [ x] **I have added comments next to my changes in GitHub to help reviewers understand them.** ✅
- [ x] I have tested my changes and ensured they work as expected.
- [ x] I have added necessary documentation (if applicable).
- [ x] This PR does not introduce any breaking changes.

edit contact us and homepage to display correct email and phone number

---

src/components/dashboard/UserProfileSection.tsx
src/components/home/art.tsx

#
continuation of Andres previous code
no longer does the load image button, loads right away if user has any photos
upload works same as Andres - but now shows the image they uploaded
delete still works the same
one issue though, the gallery slideshow only shows images of the signed in user
it will not show images of other users that have uploaded
<https://littleeinsteinchildcare.atlassian.net/browse/LEC-90>
1. user uploads go to gallery
2. load images right away, and the image previews now work 
1. fetch
2. npm run dev

LEC-90 user add photos

---

src/main.tsx

oopsie dasier
#
<https://littleeinsteinchildcare.atlassian.net/browse/LEC-##>
1. Change 1
2. Change 2
1. Step 1
2. Step 2

forgot i commeted out banner stuff

---

src/components/auth-ui/signUp.tsx
src/components/calendar/Calendar.tsx
src/components/calendar/EventEditForm.tsx
src/components/calendar/EventForm.tsx
src/components/calendar/ParentSelector.tsx
src/components/dashboard/AdminDashboard.tsx
src/components/dashboard/EmailInvitation.tsx
src/components/dashboard/UserManagement.tsx
src/components/dashboard/UserProfileSection.tsx
src/components/footer/footerConnectLinks.tsx
src/components/footer/footerContactLinks.tsx
src/components/home/about.tsx
src/components/home/testimonials.tsx
src/components/home/welcome.tsx
src/components/navbar/Navbar.tsx
src/i18n/en.ts
src/i18n/es.ts
src/main.tsx
src/pages/aboutUs/AboutUs.tsx
src/pages/calendar/Calendar.tsx
src/pages/calendar/Events.tsx
src/pages/profile/Profile.tsx
src/pages/resources/Resources.tsx

#
added testimonial updates
added andres changes from closed PR
navbar on mobile can use esc key to leave or click anywhere outside
buttons and text size repsonsiveness etc and other responsiveness layout stuff
color matching stuff
<https://littleeinsteinchildcare.atlassian.net/browse/LEC-129>
1. added testimonials
2. made calendar more responsive
3. other responsiveness and visual stuff
1. pull
2. npm run dev

testimonials update + responsiveness/visual fixes

---

src/components/footer/footerConnectLinks.tsx

#
<https://littleeinsteinchildcare.atlassian.net/browse/LEC-##>
1. Change 1
2. Change 2
1. Step 1
2. Step 2

Yelp link, still no google link
